# Reference: https://github.com/air-verse/air/blob/master/air_example.toml

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -tags development -o bin/my-app"
exclude_dir = ["bin"]
exclude_file = ["air.toml", "Makefile"]
bin = "bin/my-app"
stop_on_error = true
send_interrupt = true
